/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const {
  createPlatformBundleMetroConfig,
} = require('@office-iss/sdx-metro-config');

const {
  exclusionList,
  resolveUniqueModule,
} = require("@rnx-kit/metro-config")

const [reactIsPath, reactIsExcludePattern] = resolveUniqueModule('react-is')
const additionalExclusions = [reactIsExcludePattern]

module.exports = createPlatformBundleMetroConfig({
  resolver: { 
    // .pack files are generated by later part of devmain build, and cause Disallowed file accesses from domino.
    blockList: [/.*\.pack\.*/, exclusionList(additionalExclusions)],
    blacklistRE: [/.*\.pack.*/, exclusionList(additionalExclusions)],
    extraNodeModules: {
      "react-is": reactIsPath,
    }
  },
});
