// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the TS2DS compiler.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

import { RekaServiceInfos, RekaServiceRegistry } from '@office-iss/reka';
import { NativeService } from './AwesomeRekaDefs';

export const ServiceInfos: RekaServiceInfos = {
  NativeService: ['reacthostapp::NativeService', {
    tryCall: ['FireAndForgetMethod', ['$string', '$number']],
  }],
};

export const NativeServices = {
  NativeService: <NativeService>RekaServiceRegistry.getNativeService(ServiceInfos.NativeService),
};

export type {
  NativeService
} from './AwesomeRekaDefs';