#pragma once
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the TS2DS compiler.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include "AwesomeRekaDefs.g.h"

namespace Mso { namespace JSHost {

//================================================================================
// Service implementation (C++)
//================================================================================

void DataService<::reacthostapp::NativeService>::InvokeWithReader(const char* methodName, Mso::JSHost::IRekaReader& argumentsReader, Mso::TCntPtr<IRekaResult>&& result) noexcept
{
	(void)argumentsReader, (void)result;
	if (IsSameMethodName(methodName, "tryCall"))
	{
		std::string input1;
		int32_t input2;
		ArgsFromReader(argumentsReader, input1, input2);
		this->tryCall(std::move(input1), std::move(input2));
	}
	else
	{
		UnknownMethod(methodName);
	}
}

}} // namespace Mso::JSHost
